conditioning:
  main_sampler: resample
  method: ps # Do not touch
  params:
    scale: 0.1 # Try changing this

data:
  name: ffhq
  root: ./data/samples/

measurement:
  operator:
    name: super_resolution
    in_shape: !!python/tuple [1, 3, 256, 256]
    scale_factor: 4
  
  noise: 
    name: gaussian
    sigma: 0.01
